from .utils import StrEnum


class CreditType(StrEnum):
    HUP_SUBSIDY = "HOUSING AND URBAN PLANNING SUBSIDY"
    TREASURY_SUBSIDY = "TREASURY SUBSIDY"
    WORKING_CAPITAL = "WORKING CAPITAL"
    FACTORING = "FACTORING"
