from .utils import StrEnum


class CreditType(StrEnum):
    HUP_SUBSIDY = "HOUSING AND URBAN PLANNING SUBSIDY"
    TREASURY_SUBSIDY = "TREASURY SUBSIDY"
    WORKING_CAPITAL = "WORKING CAPITAL"
    STATE_SUBSIDY = "STATE SUBSIDY"  # TODO: Validate if it's going to be used
    BULLET_LOAN = "BULLET LOAN"
    FACTORING = "FACTORING"
    UNKNOWN = "UNKNOWN"
